name: Build Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Passe dies an deine Node.js-Version an
          cache: 'npm'

      - name: Install npm dependencies
        run: npm ci

      - name: Set up Ruby for Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Passe dies an deine Jekyll-Version an
          bundler-cache: true

      - name: Build site
        run: |
          bundle exec jekyll build --destination dist
          npm run build

      - name: List build output (Debug)
        run: ls -la dist/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/